# Ejercicios NumPy

Esta serie de ejercicios tienen como objetivo que comprueben los conocimientos adquiridos. Inicial con ejercicios simples y se se complican gradualmente.

#### Importación de NumPy 

In [1]:
import numpy as np

#### Crear un arreglo de 5 ceros  

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### Crear un arreglo de 10 unos

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un arreglo de 5  cincos 

In [10]:
a= 5*(np.ones(5))
print(a)

[5. 5. 5. 5. 5.]


#### Crear un arreglo de números consecutivos empezando en 10 terminando en 30  

In [14]:
np.arange(10,31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

#### Crear un arreglo de todos los  números pares  empezando en 10 terminando en 30  

In [17]:
np.arange(10,31,2) 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

#### Crear  un matriz  de 3x3  formada por números consecutivos del 0 al 8 

In [28]:
arreglo= np.arange(0,9)
arreglo.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crear una matriz identidad  de 5x5

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Crear un número aleatorio entre 0 y 10

In [36]:
np.random.randint(1.0,10.0)

6

#### Generen un arreglo de 20 elementos aleatorios  usando una distribución normal estándar 

In [37]:
np.random.randn(20)

array([-0.63072409, -0.80105967, -0.52990175,  0.11461869,  1.82063854,
       -1.19322489,  0.5418863 ,  0.03110714, -0.17449745, -0.03283242,
       -1.39437598,  0.18016769, -0.33673693, -1.16802422,  0.87315681,
        1.61953841,  0.09484551,  1.40904651, -1.42247678, -0.66296065])

#### Crear la siguiente matriz 

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [42]:
arreglo= np.arange(0.01,1.01,.01)
arreglo=arreglo.reshape(10,10)
print(arreglo)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Crear un arreglo de 20 elementos equidistantes entre los valores de 0 a 1 

In [44]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexación en arreglos numpy 

En esta sección se evaluará su conocimiento para obtener pociones de la matriz generada, para replicarlo tienen que usar exclusivamente  indexación 

In [106]:
matriz1= np.arange(1,26)
matriz1=matriz1.reshape(5,5)
matriz1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Extraer la siguiente matriz: 
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [117]:
mayores= matriz1[matriz1>11] 
mayores = mayores[mayores!=16]
mayores = mayores[mayores!=21]
mayores.reshape(3,4)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

Extraer la siguiente celda:  15

In [116]:
mayores[3]
#mat[2,4]

15

Extraer la siguiente matriz: 
    array([[ 2],
       [ 7],
       [12]])

In [87]:
matriz= [list(matriz1[matriz1==2]), list(matriz1[matriz1==7]), list(matriz1[matriz1==12])]
matriz

[[2], [7], [12]]

Extraer la siguiente matriz:  array([21, 22, 23, 24, 25])

In [89]:
matriz_=matriz1[matriz1>20]
matriz_

array([21, 22, 23, 24, 25])

Extraer la siguiente matriz: 
    array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [115]:
matriz__=matriz1[3:5]
matriz__

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Operaciones adiciones 

No todo puede ser cubierto por el curso sin embargo existen funciones para hacerlo [funciones universales](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)


Obtener la suma de todos los valores en la matriz **mat**

In [94]:
sum(matriz__)

205

Obtener la desviación estándar de la matriz **mat**

In [97]:
np.std(matriz__)

2.8722813232690143

Obtener la suma de cada una de las columnas en  la matriz **mat**

In [109]:
s = np.add.reduce(matriz1, axis=0)
s

array([55, 60, 65, 70, 75])

# Buen trabajo 